title: МАТРАЦИ ЛАТЕКС РУСЕ - ВАШИЯТ КОМФОРТ Е НАШ ПРИОРИТЕТ
email: latex@gmail.com
phone: +359 894 558 601
description: ВАШИЯТ КОМФОРТ Е НАШ ПРИОРИТЕТ.
# baseurl: "/site-project" 
url: "" 
twitter_username: vkolicov
github_username:  vkolicov
destination: docs


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# exclude:
#   - docs
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
